#undef TAPPING_TERM
#define TAPPING_TERM 105

#define USB_SUSPEND_WAKEUP_DELAY 0
#define NO_AUTO_SHIFT_TAB
#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "AEgne/x9B4nL"
#define LAYER_STATE_8BIT

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

