#define FLOW_TAP_TERM 200
#undef DEBOUNCE
#define DEBOUNCE 1

#undef TAPPING_TERM
#define TAPPING_TERM 250

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 300000

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 15

#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 9

#define SERIAL_NUMBER "erwYr/yoMeKl"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

