#undef TAPPING_TERM
#define TAPPING_TERM 180

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 15

#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY 15

#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 35

#define AUTO_SHIFT_TIMEOUT 125
#define NO_AUTO_SHIFT_TAB
#define NO_AUTO_SHIFT_SPECIAL
#define NO_AUTO_SHIFT_NUMERIC
#define SERIAL_NUMBER "6qMVr/dPM5lG"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

