#undef TAPPING_TERM
#define TAPPING_TERM 150

#define USB_SUSPEND_WAKEUP_DELAY 0
#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "EaoKY/Lvq0RA"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

