name: Build layout

on:
  workflow_dispatch:
    inputs:
      layout_id:
        description: "Layout id available in URL https://configure.zsa.io/voyager/layouts/[ID_IS_HERE]/latest"
        required: true
        default: "g7jjw"
      layout_geometry:
        description: "Keyboard type"
        type: choice
        options:
          - voyager
          - moonlander
          - ergodox_ez
          - ergodox_ez/stm32/glow
          - ergodox_ez/stm32/shine
          - ergodox_ez/m32u4/glow
          - ergodox_ez/m32u4/shine
          - planck_ez
          - planck_ez/glow
        default: voyager

permissions:
  contents: write

jobs:
  build-layout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download the full history for the merge to work correctly
        run: git pull --unshallow

      - name: Checkout the right firmware branch
        id: firmware
        run: |
          firmware_version="$(cat ${{ github.event.inputs.layout_id }}/firmware_version)"
          echo firmware_version=${firmware_version} >> "$GITHUB_OUTPUT"
          cd qmk_firmware
          git submodule update --init --remote
          git fetch origin firmware${firmware_version}
          git checkout -B firmware${firmware_version} origin/firmware${firmware_version}
          git submodule update --init --recursive

      - name: Build qmk docker image
        run: docker build -t qmk .

      - name: Build the layout
        id: build-layout
        run: |
          # Set keyboard directory and make prefix based on firmware version
          if [ "${{ steps.firmware.outputs.firmware_version }}" -ge 24 ]; then
            keyboard_directory="qmk_firmware/keyboards/zsa"
            make_prefix="zsa/"
          else
            keyboard_directory="qmk_firmware/keyboards"
            make_prefix=""
          fi

          # Copy layout files to the qmk folder
          rm -rf ${keyboard_directory}/${{ github.event.inputs.layout_geometry }}/keymaps/${{ github.event.inputs.layout_id }}
          mkdir -p ${keyboard_directory}/${{ github.event.inputs.layout_geometry }}/keymaps && cp -r ${{ github.event.inputs.layout_id }} "$_"

          # Build the layout
          docker run -v ./qmk_firmware:/root --rm qmk /bin/sh -c "
            qmk setup zsa/qmk_firmware -b firmware${{ steps.firmware.outputs.firmware_version }} -y
            make ${make_prefix}${{ github.event.inputs.layout_geometry }}:${{ github.event.inputs.layout_id }}
          "

          # Find and export built layout          
          normalized_layout_geometry="$(echo "${{ github.event.inputs.layout_geometry }}" | sed 's/\//_/g')"
          echo built_layout_file=$(find ./qmk_firmware -maxdepth 1 -type f -regex ".*${normalized_layout_geometry}.*\.\(bin\|hex\)$") >> "$GITHUB_OUTPUT"
          echo normalized_layout_geometry=${normalized_layout_geometry} >> "$GITHUB_OUTPUT"

      - name: Upload layout
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build-layout.outputs.normalized_layout_geometry }}_${{ github.event.inputs.layout_id }}
          path: ${{ steps.build-layout.outputs.built_layout_file }}
