#undef TAPPING_TERM
#define TAPPING_TERM 150

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "6JJgq/XbbVAP"
#define LAYER_STATE_16BIT

#define RGB_MATRIX_STARTUP_SPD 60


// custom
#define OS_DETECTION_KEYBOARD_RESET
#define OS_DETECTION_SINGLE_REPORT
